# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'

target 'ChatLingo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Networking
  pod 'Alamofire', '~> 5.8'
  
  # Keychain for secure storage
  pod 'KeychainSwift', '~> 20.0'
  
  # UI and animations
  pod 'lottie-ios', '~> 4.3'
  pod 'SnapKit', '~> 5.6' # For programmatic AutoLayout when needed
  
  # Audio processing
  pod 'AVAudioEngine'
  
  # JSON handling
  pod 'SwiftyJSON', '~> 5.0'
  
  # Image loading and caching
  pod 'Kingfisher', '~> 7.0'
  
  # Core Data helpers
  pod 'CoreStore', '~> 9.0'
  
  # Development and debugging
  pod 'SwiftLint', '~> 0.50'
  
  target 'ChatLingoTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Quick', '~> 7.0'
    pod 'Nimble', '~> 12.0'
  end

  target 'ChatLingoUITests' do
    # Pods for testing
  end

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
    end
  end
end